### ISSUE TITLE
Response FB

### ISSUE THREAD

**Issue by programmermager** [phanan/vue-facebook-signin-button#2]
its the data what we get its only name and id? how if i want to get more data like email, phone number, birthday etc. is it possible?

**Comment by ddo** [comment]
add more scope and also set the facebook app permissions

**Comment by samirph** [comment]
I had the same issue. The scope was correct and the facebook app config had the correct permissions.
Still, it was a bit difficult to find that in here:

```
      FB.api('/me', dude => {
        console.log(`Good to see you, ${dude.name}.`)
      })

```
You should add an object with a attribute "fields" to get the fields I wanted like this:
```

FB.api(
        '/me',
        'GET',
        {'fields': 'email,name'},
        dude => {
          console.log(dude)
          console.log(`Good to see you, ${dude.name}.`)
        }
      )
```
Wouldn't work in my project otherwise.

**Comment by volkanozyilmaz** [comment]
Hey @phanan Could you update your doc with this sample 

`FB.api(
        '/me',
        'GET',
        {'fields': 'email,name'},
        dude => {
          console.log(dude)
          console.log(`Good to see you, ${dude.name}.`)
        }
      )`

please. It takes time to find it here.

**Comment by phanan** [comment]
This has nothing to do with the plugin. You should know your away around FB's API.
